name: Deploy to Laragon

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: flutter pub get
      - run: flutter build web --base-href /hello-flutter/

      - name: Deploy to Laragon
        run: |
            if (Test-Path "E:\Project\laragon\www\hello-flutter") {
            Remove-Item "E:\Project\laragon\www\hello-flutter" -Recurse -Force
            }
            New-Item -ItemType Directory -Path "E:\Project\laragon\www\hello-flutter"
            Copy-Item "build\web\*" "E:\Project\laragon\www\hello-flutter" -Recurse -Force
